LPLC_rev02/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LPLC_rev02.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        public ActionResult _Blog()
        {
            return View();
        }
    }
}

LPLC_rev02/Controllers/LearnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LPLC_rev02.Controllers
{
    public class LearnController : Controller
    {
        // GET: Learn
        public ActionResult _Learn()
        {
            return View();
        }
    }
}

LPLC_rev02/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LPLC_rev02.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        public ActionResult _Search()
        {
            return View();
        }
    }
}

LPLC_rev02/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Learn PLC</title>


    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")
    
    <link href="~/Content/cybor.css" rel="stylesheet" type="text/css" />
    
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>


                @Html.ActionLink("Learn PLC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                    <li>@Html.ActionLink("Блог", "_Blog", "Blog")</li>
                    <li>@Html.ActionLink("Кодинг", "_Learn", "Learn")</li>
                    <li>@Html.ActionLink("О проекте", "About", "Home")</li>
                    <li>@Html.ActionLink("Поиск", "_Search", "Search")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>